# 04 - Exchange Rate API

El objetivo de este notebook es obtener datos históricos de tipo de cambio mediante una API externa e incorporarlos al proyecto.

Esta información permitirá analizar el posible impacto de las fluctuaciones monetarias sobre los costes de aprovisionamiento y el valor del inventario.

In [1]:
#Importar librerias
import pandas as pd
import requests

In [2]:
#Conectar con API Frankfurter

url = "https://api.frankfurter.app/latest?from=USD&to=EUR"

response = requests.get(url)

response.json()

{'amount': 1.0, 'base': 'USD', 'date': '2026-06-02', 'rates': {'EUR': 0.85844}}

La API Frankfurter fue seleccionada para el proyecto debido a que es gratuita, no requiere autenticación y permite acceder a datos históricos de tipos de cambio de forma sencilla.

In [3]:
#Extracción de datos históricos para el 2024, ya que nuestro dataset tiene datos referentes a 2024.
url = "https://api.frankfurter.app/2024-01-01..2024-12-30?from=USD&to=EUR"

response = requests.get(url)

data = response.json()

list(data.keys())

['amount', 'base', 'start_date', 'end_date', 'rates']

In [4]:
len(data["rates"])

256

In [5]:
fx_df = pd.DataFrame.from_dict(
    data["rates"],
    orient="index"
)

fx_df.head()

                EUR
2023-12-29  0.90498
2024-01-02  0.91274
2024-01-03  0.91583
2024-01-04  0.91299
2024-01-05  0.91567

In [6]:
fx_df.reset_index(inplace=True)

fx_df.columns = [
    "date",
    "usd_eur_rate"
]

In [7]:
fx_df.head(10)

         date  usd_eur_rate
0  2023-12-29       0.90498
1  2024-01-02       0.91274
2  2024-01-03       0.91583
3  2024-01-04       0.91299
4  2024-01-05       0.91567
5  2024-01-08       0.91358
6  2024-01-09       0.91408
7  2024-01-10       0.91358
8  2024-01-11       0.91017
9  2024-01-12       0.91391

In [8]:
fx_df["date"] = pd.to_datetime(fx_df["date"])

fx_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          256 non-null    datetime64[us]
 1   usd_eur_rate  256 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 4.1 KB

In [9]:
fx_df.shape

(256, 2)

In [10]:
fx_df["usd_eur_rate"].describe().round(4)

count    256.0000
mean       0.9239
std        0.0148
min        0.8932
25%        0.9158
50%        0.9223
75%        0.9311
max        0.9625
Name: usd_eur_rate, dtype: float64

Durante 2024 el tipo de cambio USD/EUR osciló entre 0,8932 y 0,9625 euros por dólar.

Estas variaciones pueden influir en los costes de aprovisionamiento cuando las compras se realizan en dólares y la compañía reporta sus resultados en euros.

In [11]:
#Vamos a hacer merge del dataset y la API

df = pd.read_csv("../Datasets/SC_clean_dataset.csv")

df["date"] = pd.to_datetime(df["date"])

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 91250 entries, 0 to 91249
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     91250 non-null  datetime64[us]
 1   sku_id                   91250 non-null  str
 2   warehouse_id             91250 non-null  str
 3   supplier_id              91250 non-null  str
 4   region                   91250 non-null  str
 5   units_sold               91250 non-null  int64
 6   inventory_level          91250 non-null  int64
 7   supplier_lead_time_days  91250 non-null  int64
 8   reorder_point            91250 non-null  int64
 9   order_quantity           91250 non-null  int64
 10  unit_cost                91250 non-null  float64
 11  unit_price               91250 non-null  float64
 12  promotion_flag           91250 non-null  bool
 13  stockout_flag            91250 non-null  bool
 14  demand_forecast          91250 non-null  float64
 15  inventory_value          91250 non-null  float64
 16  procurement_spend        91250 non-null  float64
 17  forecast_error           91250 non-null  float64
 18  abs_forecast_error       91250 non-null  float64
 19  inventory_coverage       90358 non-null  float64
 20  replenishment_flag       91250 non-null  int64
dtypes: bool(2), datetime64[us](1), float64(8), int64(6), str(4)
memory usage: 13.4 MB

In [13]:
df.shape

(91250, 21)

In [14]:
df.head(10)

,date,sku_id,warehouse_id,supplier_id,region,units_sold,inventory_level,supplier_lead_time_days,reorder_point,order_quantity,...,unit_price,promotion_flag,stockout_flag,demand_forecast,inventory_value,procurement_spend,forecast_error,abs_forecast_error,inventory_coverage,replenishment_flag
0,2024-01-01,SKU_1,WH_1,SUP_8,West,10,592,14,379,0,...,20.48,False,False,8.52,8258.40,0.0,1.48,1.48,69.483568,0
1,2024-01-02,SKU_1,WH_1,SUP_8,West,17,575,14,379,0,...,20.48,False,False,18.63,8021.25,0.0,-1.63,1.63,30.864198,0
2,2024-01-03,SKU_1,WH_1,SUP_8,North,35,540,14,379,0,...,20.48,True,False,39.62,7533.00,0.0,-4.62,4.62,13.629480,0
3,2024-01-04,SKU_1,WH_1,SUP_8,South,24,516,14,379,0,...,20.48,False,False,19.43,7198.20,0.0,4.57,4.57,26.556871,0
4,2024-01-05,SKU_1,WH_1,SUP_8,West,21,495,14,379,0,...,20.48,False,False,18.70,6905.25,0.0,2.30,2.30,26.470588,0
5,2024-01-06,SKU_1,WH_1,SUP_8,East,18,477,14,379,0,...,20.48,False,False,18.33,6654.15,0.0,-0.33,0.33,26.022913,0
6,2024-01-07,SKU_1,WH_1,SUP_8,North,19,458,14,379,0,...,20.48,False,False,18.91,6389.10,0.0,0.09,0.09,24.219989,0
7,2024-01-08,SKU_1,WH_1,SUP_8,North,23,435,14,379,0,...,20.48,True,False,25.84,6068.25,0.0,-2.84,2.84,16.834365,0
8,2024-01-09,SKU_1,WH_1,SUP_8,West,25,410,14,379,0,...,20.48,False,False,21.70,5719.50,0.0,3.30,3.30,18.894009,0
9,2024-01-10,SKU_1,WH_1,SUP_8,South,25,385,14,379,0,...,20.48,False,False,21.34,5370.75,0.0,3.66,3.66,18.041237,0

## Integración de datos

Se realiza una unión entre el dataset principal de Supply Chain y los tipos de cambio históricos obtenidos mediante la API Frankfurter.

La unión se realiza utilizando la fecha como clave común.

In [15]:
df_final = df.merge(
    fx_df,
    on="date",
    how="left"
)

In [16]:
df_final.shape

(91250, 22)

In [17]:
df_final.head(10)

,date,sku_id,warehouse_id,supplier_id,region,units_sold,inventory_level,supplier_lead_time_days,reorder_point,order_quantity,...,promotion_flag,stockout_flag,demand_forecast,inventory_value,procurement_spend,forecast_error,abs_forecast_error,inventory_coverage,replenishment_flag,usd_eur_rate
0,2024-01-01,SKU_1,WH_1,SUP_8,West,10,592,14,379,0,...,False,False,8.52,8258.40,0.0,1.48,1.48,69.483568,0,NaN
1,2024-01-02,SKU_1,WH_1,SUP_8,West,17,575,14,379,0,...,False,False,18.63,8021.25,0.0,-1.63,1.63,30.864198,0,0.91274
2,2024-01-03,SKU_1,WH_1,SUP_8,North,35,540,14,379,0,...,True,False,39.62,7533.00,0.0,-4.62,4.62,13.629480,0,0.91583
3,2024-01-04,SKU_1,WH_1,SUP_8,South,24,516,14,379,0,...,False,False,19.43,7198.20,0.0,4.57,4.57,26.556871,0,0.91299
4,2024-01-05,SKU_1,WH_1,SUP_8,West,21,495,14,379,0,...,False,False,18.70,6905.25,0.0,2.30,2.30,26.470588,0,0.91567
5,2024-01-06,SKU_1,WH_1,SUP_8,East,18,477,14,379,0,...,False,False,18.33,6654.15,0.0,-0.33,0.33,26.022913,0,NaN
6,2024-01-07,SKU_1,WH_1,SUP_8,North,19,458,14,379,0,...,False,False,18.91,6389.10,0.0,0.09,0.09,24.219989,0,NaN
7,2024-01-08,SKU_1,WH_1,SUP_8,North,23,435,14,379,0,...,True,False,25.84,6068.25,0.0,-2.84,2.84,16.834365,0,0.91358
8,2024-01-09,SKU_1,WH_1,SUP_8,West,25,410,14,379,0,...,False,False,21.70,5719.50,0.0,3.30,3.30,18.894009,0,0.91408
9,2024-01-10,SKU_1,WH_1,SUP_8,South,25,385,14,379,0,...,False,False,21.34,5370.75,0.0,3.66,3.66,18.041237,0,0.91358

In [18]:
#Vamos a ver cuanto valores nulos tenemos tras la union, ya que la API sólo tiene días laborables y el dataset tiene todos los días del año
df_final["usd_eur_rate"].isna().sum()

np.int64(27500)

In [19]:
#Vamos a rellenar los valores nulos con el último valor disponible. Rellena fines de semana y festivos con el ultimo valor conocido
df_final["usd_eur_rate"] = df_final["usd_eur_rate"].ffill()

In [20]:
df_final["usd_eur_rate"].isna().sum()

np.int64(1)

In [ ]:
#Corrige el posible valor nulo inicial que nos encontramos arriba. 
df_final["usd_eur_rate"] = df_final["usd_eur_rate"].bfill()

In [22]:
df_final["usd_eur_rate"].isna().sum()

np.int64(0)

Tras aplicar forward fill, permanecía un valor nulo al inicio del periodo porque no existía una cotización anterior disponible. Para resolverlo, se aplicó backward fill utilizando la primera cotización disponible posterior.

## Contexto de negocio

En operaciones internacionales es habitual que los costes de aprovisionamiento, transporte o producción se negocien en dólares estadounidenses (USD), mientras que los clientes finales pueden solicitar la facturación en euros (EUR).

Para simular este escenario, se asume que los costes del dataset están expresados en USD y se convierten a EUR utilizando tipos de cambio históricos obtenidos mediante una API externa.

Esta aproximación permite evaluar cómo las fluctuaciones monetarias pueden afectar al coste final de las operaciones y al valor financiero del inventario.

### Procurement Spend - EUR

¿Cuál es el coste de aprovisionamiento en euros considerando el tipo de cambio histórico?

In [23]:
df_final["procurement_spend_eur"] = (df_final["procurement_spend"] * df_final["usd_eur_rate"])

In [24]:
df_final[["procurement_spend", "usd_eur_rate", "procurement_spend_eur"]].head()

   procurement_spend  usd_eur_rate  procurement_spend_eur
0                0.0       0.91274                    0.0
1                0.0       0.91274                    0.0
2                0.0       0.91583                    0.0
3                0.0       0.91299                    0.0
4                0.0       0.91567                    0.0

In [25]:
df_final["procurement_spend_eur"].describe().round(2)

count    91250.00
mean       217.86
std        997.41
min          0.00
25%          0.00
50%          0.00
75%          0.00
max       9267.33
Name: procurement_spend_eur, dtype: float64

In [26]:
#Vamos a calcular con procurement_spend mayor a cero

df_final[
    df_final["procurement_spend"] > 0
][[
    "procurement_spend",
    "usd_eur_rate",
    "procurement_spend_eur"
]].head(10)

     procurement_spend  usd_eur_rate  procurement_spend_eur
11             6556.50       0.91391            5992.050915
30             5538.15       0.92276            5110.383294
45             4784.85       0.93084            4453.929774
58             3417.75       0.92524            3162.239010
66             2957.40       0.91785            2714.449590
73             2845.80       0.91533            2604.846114
81             3431.70       0.92396            3170.753532
89             6458.85       0.92498            5974.307073
102            6305.40       0.93879            5919.446466
118            5259.15       0.93336            4908.680244

In [27]:
df_final["procurement_spend_eur"].describe().round(2)

count    91250.00
mean       217.86
std        997.41
min          0.00
25%          0.00
50%          0.00
75%          0.00
max       9267.33
Name: procurement_spend_eur, dtype: float64

### Conclusión

Tras incorporar los tipos de cambio históricos USD/EUR, el gasto medio de aprovisionamiento pasa de 235,26 USD a 217,86 EUR.

La diferencia observada refleja el impacto potencial de las fluctuaciones monetarias sobre los costes de compra en operaciones internacionales, especialmente cuando los costes se generan en dólares y la facturación o reporting financiero se realiza en euros.

### Inventory Value - EUR

¿Cuál es el valor de inventario en euros teniendo en cuenta el tipo de cambio?

In [29]:
df_final["inventory_value_eur"] = (df_final["inventory_value"] * df_final["usd_eur_rate"])

In [30]:
df_final[["inventory_value", "usd_eur_rate", "inventory_value_eur"]].head()

   inventory_value  usd_eur_rate  inventory_value_eur
0          8258.40       0.91274          7537.772016
1          8021.25       0.91274          7321.315725
2          7533.00       0.91583          6898.947390
3          7198.20       0.91299          6571.884618
4          6905.25       0.91567          6322.930267

In [31]:
df_final["inventory_value_eur"].describe().round(2)

count    91250.00
mean      5320.56
std       2578.92
min       1010.96
25%       3255.98
50%       4849.17
75%       6957.54
max      18371.32
Name: inventory_value_eur, dtype: float64

### Conclusión

Tras incorporar los tipos de cambio históricos USD/EUR, el valor medio del inventario pasa de aproximadamente 5.756 USD a 5.321 EUR.

Este análisis permite simular el impacto financiero que las fluctuaciones monetarias pueden tener sobre el valor del stock cuando los costes se generan en dólares y el reporting financiero se realiza en euros.

### FX Impact

¿Cuál es el impacto potencial de la conversion USD a EUR sobre los costes de aprovisionamiento?

In [34]:
df_final[df_final["fx_impact"] > 0
][["procurement_spend", "procurement_spend_eur", "fx_impact"]].head(10)

     procurement_spend  procurement_spend_eur   fx_impact
11             6556.50            5992.050915  564.449085
30             5538.15            5110.383294  427.766706
45             4784.85            4453.929774  330.920226
58             3417.75            3162.239010  255.510990
66             2957.40            2714.449590  242.950410
73             2845.80            2604.846114  240.953886
81             3431.70            3170.753532  260.946468
89             6458.85            5974.307073  484.542927
102            6305.40            5919.446466  385.953534
118            5259.15            4908.680244  350.469756

In [35]:
df_final["fx_impact"].describe().round(2)

count    91250.00
mean        17.40
std         80.89
min          0.00
25%          0.00
50%          0.00
75%          0.00
max        978.91
Name: fx_impact, dtype: float64

In [36]:
df_final["fx_impact"].sum().round(2)

np.float64(1588060.65)

In [37]:
df_final[df_final["procurement_spend"] > 0]["fx_impact"].describe().round(2)

count    5027.00
mean      315.91
std       156.48
min        41.63
25%       194.08
50%       286.10
75%       413.55
max       978.91
Name: fx_impact, dtype: float64

### Conclusiones

El impacto acumulado del tipo de cambio durante el periodo analizado asciende a aproximadamente 1,59 millones.

Este resultado refleja cómo las fluctuaciones monetarias pueden influir en los costes de aprovisionamiento cuando las operaciones se realizan en USD y el reporting financiero se realiza en EUR.

Aunque el dataset es una simulación, este escenario reproduce una situación habitual en cadenas de suministro internacionales.

In [38]:
df_final.to_csv("../Datasets/Dataset_final+API.csv", index=False)

### Conexión Python - SQL

In [39]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\Users\pilir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.49)
Requirement already satisfied: pymysql in c:\Users\pilir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.1.2)
Requirement already satisfied: greenlet>=1 in c:\Users\pilir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\pilir\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [41]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:27021999@localhost/supply_chain_control_tower"
)

df_final.to_sql(
    "supply_chain",
    con=engine,
    if_exists="replace",
    index=False
)

91250